steps:
  # Build and push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.frontend', '-t', 'gcr.io/$PROJECT_ID/ai-stock-trading-frontend:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-stock-trading-frontend:latest']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ai-stock-trading-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-stock-trading-frontend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=https://ai-stock-trading-api-1012090067429.us-central1.run.app'

images:
  - 'gcr.io/$PROJECT_ID/ai-stock-trading-frontend:latest'