steps:
  # Build trading bot image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-trading-bot:$BUILD_ID', '-f', 'Dockerfile.trading-bot', '.']
    
  # Push trading bot image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-trading-bot:$BUILD_ID']
    
  # Deploy trading bot to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ai-trading-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-trading-bot:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'FLASK_ENV=production'
      - '--set-env-vars'
      - 'PYTHONPATH=/app'

images:
  - 'gcr.io/$PROJECT_ID/ai-trading-bot:$BUILD_ID'
