steps:
  # Build frontend static image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-stock-trading-frontend:$BUILD_ID', '-f', 'Dockerfile.static', '.']
    
  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-stock-trading-frontend:$BUILD_ID']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ai-stock-trading-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-stock-trading-frontend:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=https://ai-stock-trading-backend-ccrwk2lv6q-uc.a.run.app'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/ai-stock-trading-frontend:$BUILD_ID'
