steps:
  # Build simple backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-stock-trading-backend-simple:latest', '-f', 'Dockerfile.simple-backend', '.']
    
  # Push simple backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-stock-trading-backend-simple:latest']
    
  # Deploy simple backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ai-stock-trading-backend-simple'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-stock-trading-backend-simple:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'

images:
  - 'gcr.io/$PROJECT_ID/ai-stock-trading-backend-simple:latest'