steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'deployment/Dockerfile.frontend', '-t', 'gcr.io/$PROJECT_ID/ai-stock-trading-frontend', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-stock-trading-frontend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ai-stock-trading-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-stock-trading-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--min-instances'
      - '0'

images:
  - 'gcr.io/$PROJECT_ID/ai-stock-trading-frontend'