import React, { useState } from 'react';
import { 
  DocumentArrowDownIcon, 
  XMarkIcon,
  CheckIcon,
  ClockIcon,
  UserIcon,
  SparklesIcon
} from '@heroicons/react/24/outline';

const ExportChat = ({ 
  messages, 
  chatTitle, 
  isOpen, 
  onClose, 
  isDarkMode = false 
}) => {
  const [exportFormat, setExportFormat] = useState('pdf');
  const [includeMetadata, setIncludeMetadata] = useState(true);

  const exportToPDF = () => {
    const content = generateExportContent();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${chatTitle || 'StockBroker-AI-Chat'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    onClose();
  };

  const exportToEmail = () => {
    const content = generateExportContent();
    const subject = encodeURIComponent(`StockBroker AI Chat - ${chatTitle || 'Conversation'}`);
    const body = encodeURIComponent(content);
    const mailtoLink = `mailto:?subject=${subject}&body=${body}`;
    window.open(mailtoLink);
    onClose();
  };

  const generateExportContent = () => {
    const timestamp = new Date().toLocaleString();
    let content = `StockBroker AI Chat Export\n`;
    content += `========================\n\n`;
    content += `Chat Title: ${chatTitle || 'Untitled Chat'}\n`;
    content += `Export Date: ${timestamp}\n`;
    content += `Total Messages: ${messages.length}\n\n`;
    content += `Conversation:\n`;
    content += `=============\n\n`;

    messages.forEach((message, index) => {
      const timestamp = message.timestamp.toLocaleString();
      const sender = message.type === 'user' ? 'User' : 'StockBroker AI';
      
      content += `[${index + 1}] ${sender} - ${timestamp}\n`;
      content += `${'-'.repeat(50)}\n`;
      content += `${message.content}\n\n`;
    });

    content += `\n---\n`;
    content += `Generated by StockBroker AI Assistant\n`;
    content += `Export completed: ${timestamp}\n`;

    return content;
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className={`w-full max-w-md ${isDarkMode ? 'bg-gray-800' : 'bg-white'} rounded-lg shadow-xl`}>
        <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
          <h2 className={`text-lg font-semibold ${isDarkMode ? 'text-white' : 'text-gray-900'}`}>
            Export Chat
          </h2>
          <button
            onClick={onClose}
            className={`p-1 rounded-lg hover:bg-gray-100 ${isDarkMode ? 'hover:bg-gray-700' : ''}`}
          >
            <XMarkIcon className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        <div className="p-6 space-y-4">
          <div>
            <label className={`block text-sm font-medium mb-2 ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
              Export Format
            </label>
            <div className="space-y-2">
              <label className="flex items-center">
                <input
                  type="radio"
                  value="pdf"
                  checked={exportFormat === 'pdf'}
                  onChange={(e) => setExportFormat(e.target.value)}
                  className="mr-2"
                />
                <span className={`text-sm ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                  Text File (.txt)
                </span>
              </label>
              <label className="flex items-center">
                <input
                  type="radio"
                  value="email"
                  checked={exportFormat === 'email'}
                  onChange={(e) => setExportFormat(e.target.value)}
                  className="mr-2"
                />
                <span className={`text-sm ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                  Email Transcript
                </span>
              </label>
            </div>
          </div>

          <div>
            <label className="flex items-center">
              <input
                type="checkbox"
                checked={includeMetadata}
                onChange={(e) => setIncludeMetadata(e.target.checked)}
                className="mr-2"
              />
              <span className={`text-sm ${isDarkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                Include metadata (timestamps, message count)
              </span>
            </label>
          </div>

          <div className={`p-3 rounded-lg ${isDarkMode ? 'bg-gray-700' : 'bg-gray-50'}`}>
            <p className={`text-xs ${isDarkMode ? 'text-gray-400' : 'text-gray-600'}`}>
              <strong>Export includes:</strong>
              <br />
              • Full conversation transcript
              <br />
              • Message timestamps
              <br />
              • Chat metadata
              <br />
              • {messages.length} messages total
            </p>
          </div>
        </div>

        <div className="flex items-center justify-end space-x-3 p-6 border-t border-gray-200 dark:border-gray-700">
          <button
            onClick={onClose}
            className={`px-4 py-2 text-sm font-medium rounded-lg border transition-colors ${
              isDarkMode 
                ? 'border-gray-600 text-gray-300 hover:bg-gray-700' 
                : 'border-gray-300 text-gray-700 hover:bg-gray-50'
            }`}
          >
            Cancel
          </button>
          <button
            onClick={exportFormat === 'pdf' ? exportToPDF : exportToEmail}
            className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors flex items-center space-x-2"
          >
            <DocumentArrowDownIcon className="w-4 h-4" />
            <span>Export</span>
          </button>
        </div>
      </div>
    </div>
  );
};

export default ExportChat;
